export const JAVA_QUIZ_PATHS = {
    "Data Types": {
        "ints": "/(tabs)/(home)/quizzes/java/dataTypes/strings",
        "Strings": "/(tabs)/(home)/quizzes/java/dataTypes/strings",
        "booleans": "/(tabs)/(home)/quizzes/java/dataTypes/strings",
        "Longs": "/(tabs)/(home)/quizzes/java/dataTypes/strings",
        "floats": "/(tabs)/(home)/quizzes/java/dataTypes/strings",
        "doubles": "/(tabs)/(home)/quizzes/java/dataTypes/strings",
        "shorts": "/(tabs)/(home)/quizzes/java/dataTypes/strings",
        "bytes": "/(tabs)/(home)/quizzes/java/dataTypes/strings",
        "chars": "/(tabs)/(home)/quizzes/java/dataTypes/strings",
        "Comments": "/(tabs)/(home)/quizzes/java/dataTypes/strings",
    },
    "Variables": {
        "Initializing Variables": "/(tabs)/(home)/quizzes/java/dataTypes/strings",
        "Naming Variables": "/(tabs)/(home)/quizzes/java/dataTypes/strings",
        "Assigning Values": "/(tabs)/(home)/quizzes/java/dataTypes/strings",
        "Updating Values": "/(tabs)/(home)/quizzes/java/dataTypes/strings",
        "Constants": "/(tabs)/(home)/quizzes/java/dataTypes/strings",
    },
    "For Loops": {
        "For Loops Syntax": "/(tabs)/(home)/quizzes/java/dataTypes/strings",
        "For Loops Condition": "/(tabs)/(home)/quizzes/java/dataTypes/strings",
        "Increment/Decrement": "/(tabs)/(home)/quizzes/java/dataTypes/strings",
        "Nested For Loops": "/(tabs)/(home)/quizzes/java/dataTypes/strings",
        "While Loops Syntax": "/(tabs)/(home)/quizzes/java/dataTypes/strings",
        "While Loops Condition": "/(tabs)/(home)/quizzes/java/dataTypes/strings",
        "Do While Loops": "/(tabs)/(home)/quizzes/java/dataTypes/strings",
        "For Each Syntax": "/(tabs)/(home)/quizzes/java/dataTypes/strings",
    },
    "Conditionals": {
        "If": "/(tabs)/(home)/quizzes/java/dataTypes/strings",
        "Else": "/(tabs)/(home)/quizzes/java/dataTypes/strings",
        "Elseif": "/(tabs)/(home)/quizzes/java/dataTypes/strings",
        "Multiple Ifs": "/(tabs)/(home)/quizzes/java/dataTypes/strings",
        "Multiple Elseifs": "/(tabs)/(home)/quizzes/java/dataTypes/strings",
        "If/Else Nesting": "/(tabs)/(home)/quizzes/java/dataTypes/strings",
        "Ternary": "/(tabs)/(home)/quizzes/java/dataTypes/strings",
        "Switch Syntax": "/(tabs)/(home)/quizzes/java/dataTypes/strings",
        "Switch Expressions": "/(tabs)/(home)/quizzes/java/dataTypes/strings",
        "Switch Cases": "/(tabs)/(home)/quizzes/java/dataTypes/strings",
        "Break Statement": "/(tabs)/(home)/quizzes/java/dataTypes/strings",
        "Continue Statement": "/(tabs)/(home)/quizzes/java/dataTypes/strings",
    },
    "Arrays": {
        "Initializing Arrays": "/(tabs)/(home)/quizzes/java/dataTypes/strings",
        "Assigning Values": "/(tabs)/(home)/quizzes/java/dataTypes/strings",
        "Array Indexes": "/(tabs)/(home)/quizzes/java/dataTypes/strings",
        "Updating Values": "/(tabs)/(home)/quizzes/java/dataTypes/strings",
        "Length Method": "/(tabs)/(home)/quizzes/java/dataTypes/strings",
        "Looping Through Arrays": "/(tabs)/(home)/quizzes/java/dataTypes/strings",
    },
    "Collections": {
    },
    "Methods": {
        "Method Signatures": "/(tabs)/(home)/quizzes/java/dataTypes/strings",
        "Return Types": "/(tabs)/(home)/quizzes/java/dataTypes/strings",
        "Parameters": "/(tabs)/(home)/quizzes/java/dataTypes/strings",
        "Scope": "/(tabs)/(home)/quizzes/java/dataTypes/strings",
        "Naming Methods": "/(tabs)/(home)/quizzes/java/dataTypes/strings",
        "Overloading": "/(tabs)/(home)/quizzes/java/dataTypes/strings",
    },
    "Operators": {
        "&&": "/(tabs)/(home)/quizzes/java/dataTypes/strings",
        "||": "/(tabs)/(home)/quizzes/java/dataTypes/strings",
        "!": "/(tabs)/(home)/quizzes/java/dataTypes/strings",
        "+": "/(tabs)/(home)/quizzes/java/dataTypes/strings",
        "-": "/(tabs)/(home)/quizzes/java/dataTypes/strings",
        "/": "/(tabs)/(home)/quizzes/java/dataTypes/strings",
        "*": "/(tabs)/(home)/quizzes/java/dataTypes/strings",
        "%": "/(tabs)/(home)/quizzes/java/dataTypes/strings",
        "++": "/(tabs)/(home)/quizzes/java/dataTypes/strings",
        "--": "/(tabs)/(home)/quizzes/java/dataTypes/strings",
        "<": "/(tabs)/(home)/quizzes/java/dataTypes/strings",
        ">": "/(tabs)/(home)/quizzes/java/dataTypes/strings",
        "==": "/(tabs)/(home)/quizzes/java/dataTypes/strings",
        "<=": "/(tabs)/(home)/quizzes/java/dataTypes/strings",
        ">=": "/(tabs)/(home)/quizzes/java/dataTypes/strings",
        "!=": "/(tabs)/(home)/quizzes/java/dataTypes/strings",
        "=": "/(tabs)/(home)/quizzes/java/dataTypes/strings",
    },
}