export const TERMS_AND_CONDITIONS = {
    TITLE: "Terms and Conditions",
    UPDATE_DATE: "September 5th, 2024",
    INTRODUCTION_TITLE: "1. Introduction",
    INTRODUCTION_TEXT: "Welcome to CodeJawn. These Terms and Conditions (“Terms”) govern your use of our mobile application and related services (collectively, the “Service”). By accessing or using the Service, you agree to comply with and be bound by these Terms. If you do not agree with these Terms, please do not use the Service.",
    DEFINITIONS_TITLE: "2. Definitions",
    DEFINITIONS_USER: "“User”: Any individual who accesses or uses the Service.",
    DEFINITIONS_SERVICE: "The CodeJawn application and related services.",
    DEFINITIONS_CONTENT: "All text, graphics, logos, images, and other materials provided through the Service.",
    USER_OBLIGATIONS_TITLE: "3. User Obligations",
    USER_OBLIGATIONS_ACCOUNT_CREATION: "Account Creation: You may need to create an account to access certain features. You agree to provide accurate and complete information and to update it as necessary.",
    USER_OBLIGATIONS_PROHIBITED_CONDUCT: "Prohibited Conduct: You agree not to use the Service for any unlawful purposes or in a manner that could damage, disable, or impair the Service. Prohibited activities include, but are not limited to, spamming, hacking, or distributing malware.",
    USAGE_RIGHTS_TITLE: "4. Usage Rights",
    USAGE_RIGHTS_LICENSE: "License: We grant you a limited, non-exclusive, non-transferable license to use the Service for personal, non-commercial purposes.",
    USAGE_RIGHTS_RESTRICTIONS: "Restrictions: You may not reverse engineer, decompile, or disassemble the Service. You may not use the Service for commercial purposes without our prior written consent.",
    CONTENT_OWNERSHIP_TITLE: "5. Content Ownership",
    CONTENT_OWNERSHIP_INTELLECTUAL_PROPERTY: "Intellectual Property: All rights, title, and interest in and to the Service and its Content are owned by us or our licensors.",
    CONTENT_OWNERSHIP_USER_CONTENT: "User Content: You retain ownership of any content you submit to the Service, but you grant us a worldwide, non-exclusive, royalty-free license to use, reproduce, and display such content as part of the Service.",
    PRIVACY_AND_DATA_PROTECTION_TITLE: "6. Privacy and Data Protection",
    PRIVACY_AND_DATA_PROTECTION_DATA_COLLECTION: "Data Collection: We collect and use personal data in accordance with our [Privacy Policy]. By using the Service, you consent to our data practices.",
    PRIVACY_AND_DATA_PROTECTION_DATA_SHARING: "Data Sharing: We may share your data with third parties in certain circumstances, such as with service providers or as required by law.",
    PAYMENT_AND_SUBSCRIPTIONS_TERMS_TITLE: "7. Payment and Subscription Terms",
    PAYMENT_AND_SUBSCRIPTIONS_TERMS_FEES: "Fees: Some features of the Service may require payment. You agree to pay all applicable fees as described at the point of purchase.",
    PAYMENT_AND_SUBSCRIPTIONS_TERMS_BILLING: "Billing: Payments are processed through a third-party provider. We are not responsible for payment processing errors.",
    PAYMENT_AND_SUBSCRIPTIONS_TERMS_REFUNDS: "Refunds: Refunds are handled according to our refund policy, which is available [link to refund policy].",
    THIRD_PARTY_LINKS_AND_SERVICES_TITLE: "8. Third-Party Links and Services",
    THIRD_PARTY_LINKS_AND_SERVICES_TEXT: "The Service may contain links to third-party websites or services. We are not responsible for the content or practices of these third parties. Your use of third-party services is at your own risk.",
    DISPUTE_RESOLUTION_TITLE: "9. Dispute Resolution",
    DISPUTE_RESOLUTION_GOVERNING_LAW: "Governing Law: These Terms are governed by the laws of [Your State/Country], without regard to its conflict of laws principles.",
    DISPUTE_RESOLUTION_TEXT: "Dispute Resolution: Any disputes arising out of or related to these Terms or the Service shall be resolved through [arbitration/mediation] in [Your City, State/Country].",
    LIMITATION_OF_LIABILITY_TITLE: "10. Limitation of Liability",
    LIMITATION_OF_LIABILITY_TEXT: "To the maximum extent permitted by law, we are not liable for any indirect, incidental, special, or consequential damages arising out of or in connection with your use of the Service.",
    TERMINATION_TITLE: "11. Termination",
    TERMINATION_BY_US: "Termination by Us: We may terminate or suspend your access to the Service at any time for any reason, including if you violate these Terms.",
    TERMINATION_BY_YOU: "Termination by You: You may terminate your account by contacting us at [support email].",
    CHANGES_TO_TERMS_TITLE: "12. Changes to Terms",
    CHANGES_TO_TERMS_TEXT: "We may modify these Terms from time to time. We will notify you of any material changes by posting the new Terms on the Service. Your continued use of the Service after such changes constitutes acceptance of the new Terms.",
    CONTACT_INFORMATION_TITLE: "13. Contact Information",
    CONTACT_INFORMATION_TEXT: "If you have any questions or concerns about these Terms, please contact us at:",
    SUPPORT_EMAIL: "Email: [support email]",
    MISCELLANEOUS_TITLE: "14. Miscellaneous",
    MISCELLANEOUS_ENTIRE_AGREEMENT: "Entire Agreement: These Terms constitute the entire agreement between you and us regarding the Service.",
    MISCELLANEOUS_SEVERABILITY: "Severability: If any provision of these Terms is found to be invalid or unenforceable, the remaining provisions will remain in full force and effect.",
    MISCELLANEOUS_WAIVER: "Waiver: Our failure to enforce any right or provision of these Terms will not constitute a waiver of such right or provision.",
}