logging:
  level:
    root: INFO

spring:
  mail:
    username: ""
    password: ""

URL: "http://localhost:3000"

cors:
  allowed-origins: "http://localhost:3000"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "*"
  allow-credentials: true