export interface javaOperatorsLT {
    id: number,
    andLessonIsComplete: boolean,
    orLessonIsComplete: boolean,
    notLessonIsComplete: boolean,
    plusLessonIsComplete: boolean,
    minusLessonIsComplete: boolean,
    divideLessonIsComplete: boolean,
    multiplyLessonIsComplete: boolean,
    modulusLessonIsComplete: boolean,
    incrementLessonIsComplete: boolean,
    decrementLessonIsComplete: boolean,
    lessThanLessonIsComplete: boolean,
    greaterThanLessonIsComplete: boolean,
    doubleEqualsLessonIsComplete: boolean,
    lessThanEqualToLessonIsComplete: boolean,
    greaterThanEqualToLessonIsComplete: boolean,
    notEqualToLessonIsComplete: boolean,
    equalsLessonIsComplete: boolean,
    quizIsComplete: boolean,
    complete: boolean
}

export const getDefaultJavaOperatorsLT = (): javaOperatorsLT => ({
    id: 0,
    andLessonIsComplete: false,
    orLessonIsComplete: false,
    notLessonIsComplete: false,
    plusLessonIsComplete: false,
    minusLessonIsComplete: false,
    divideLessonIsComplete: false,
    multiplyLessonIsComplete: false,
    modulusLessonIsComplete: false,
    incrementLessonIsComplete: false,
    decrementLessonIsComplete: false,
    lessThanLessonIsComplete: false,
    greaterThanLessonIsComplete: false,
    doubleEqualsLessonIsComplete: false,
    lessThanEqualToLessonIsComplete: false,
    greaterThanEqualToLessonIsComplete: false,
    notEqualToLessonIsComplete: false,
    equalsLessonIsComplete: false,
    quizIsComplete: false,
    complete: false
});